# Generated by Django 3.0.5 on 2020-05-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hola',
            field=models.CharField(default='juan', max_length=200),
        ),
    ]
