# Generated by Django 3.0.5 on 2020-05-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_profile_hola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hola',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
