# Generated by Django 3.0.5 on 2020-05-06 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20200506_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hola',
        ),
    ]
