# Generated by Django 3.0.5 on 2020-05-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='album_name',
            field=models.CharField(default='No name for this album', max_length=200),
        ),
    ]
