# Generated by Django 3.0.5 on 2020-05-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_album_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='artist_name',
            field=models.CharField(default='No artist for this album', max_length=200),
        ),
    ]
