# Generated by Django 3.0.5 on 2020-05-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_artist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='album_url',
            field=models.CharField(default='No URL for this album', max_length=2000),
        ),
    ]
