# Generated by Django 3.0.5 on 2020-05-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_album_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='creator',
            field=models.CharField(default='juan', max_length=200),
        ),
    ]
